package com.dreamingtree;

import org.apache.commons.text.similarity.LevenshteinDistance;

import java.util.Comparator;
import java.util.HashMap;
import java.util.Map;

/**
 * A static list of songs available as of 2017-07-26. These are stored instead of retrieved to improve response times.
 *
 * A https://en.wikipedia.org/wiki/Levenshtein_distance is used for string comparison.
 */
final class Songs {

    private static final LevenshteinDistance LEVENSHTEIN_DISTANCE = LevenshteinDistance.getDefaultInstance();

    private static final Map<String, Integer> SONG_IDS = new HashMap<>();

    static {
        SONG_IDS.put("#27", 473);
        SONG_IDS.put("#34", 34);
        SONG_IDS.put("#35", 592);
        SONG_IDS.put("#36", 36);
        SONG_IDS.put("#40", 40);
        SONG_IDS.put("#41", 41);
        SONG_IDS.put("(Don't Fear) The Reaper", 510);
        SONG_IDS.put("(What's So Funny 'Bout) Peace, Love and Understanding", 427);
        SONG_IDS.put("100 Years", 363);
        SONG_IDS.put("3 R's, The", 541);
        SONG_IDS.put("32/20 Blues", 652);
        SONG_IDS.put("41 Police", 199);
        SONG_IDS.put("54-46 (That's My Number)", 2825);
        SONG_IDS.put("ABC", 780);
        SONG_IDS.put("After Her", 204);
        SONG_IDS.put("After the Gold Rush", 209);
        SONG_IDS.put("Ain't No More Cane", 2801);
        SONG_IDS.put("Ain't Nothing Wrong with That", 528);
        SONG_IDS.put("Alcañiz (Festiva)", 480);
        SONG_IDS.put("All Along the Watchtower", 96);
        SONG_IDS.put("All the Same", 682);
        SONG_IDS.put("Alligator Pie", 580);
        SONG_IDS.put("Alone and Forsaken", 627);
        SONG_IDS.put("Alouette", 774);
        SONG_IDS.put("Also Sprach Zarathustra", 193);
        SONG_IDS.put("Amazing Grace", 97);
        SONG_IDS.put("American Baby", 287);
        SONG_IDS.put("American Baby Intro", 297);
        SONG_IDS.put("American Girl", 677);
        SONG_IDS.put("American Pie", 755);
        SONG_IDS.put("American Tune", 247);
        SONG_IDS.put("An' Another Thing", 327);
        SONG_IDS.put("And He Slayed Her", 649);
        SONG_IDS.put("And Then They Were Free", 633);
        SONG_IDS.put("Angel", 78);
        SONG_IDS.put("Angel Without Wings", 499);
        SONG_IDS.put("Angel from Montgomery", 98);
        SONG_IDS.put("Angels", 572);
        SONG_IDS.put("Anna Begins", 423);
        SONG_IDS.put("Another Brick in the Wall Part 2", 675);
        SONG_IDS.put("Answer Me", 500);
        SONG_IDS.put("Antichrist Superstar", 481);
        SONG_IDS.put("Ants Go Marching One by One, The", 545);
        SONG_IDS.put("Ants Marching", 17);
        SONG_IDS.put("Any Noise", 172);
        SONG_IDS.put("Anyone Seen the Bridge", 92);
        SONG_IDS.put("Aqualung", 775);
        SONG_IDS.put("As Far As We Can See", 226);
        SONG_IDS.put("Asimbonanga", 791);
        SONG_IDS.put("Awake", 749);
        SONG_IDS.put("Baby", 234);
        SONG_IDS.put("Baby Blue", 585);
        SONG_IDS.put("Baby Don't You Do It", 3875);
        SONG_IDS.put("Back to Alexandra", 99);
        SONG_IDS.put("Bad Bad", 638);
        SONG_IDS.put("Bartender", 65);
        SONG_IDS.put("Basically Frightened", 532);
        SONG_IDS.put("Bathtub Gin", 256);
        SONG_IDS.put("Be Yourself", 2830);
        SONG_IDS.put("Beach Ball", 587);
        SONG_IDS.put("Beautifully Broken", 310);
        SONG_IDS.put("Bed's Too Big Without You, The", 262);
        SONG_IDS.put("Beginning of the End, The", 676);
        SONG_IDS.put("Belly Belly Nice", 729);
        SONG_IDS.put("Belly Full", 731);
        SONG_IDS.put("Bennie and the Jets", 201);
        SONG_IDS.put("Best of What's Around, The", 4);
        SONG_IDS.put("Betrayal", 448);
        SONG_IDS.put("Big Blast of Hot Air", 221);
        SONG_IDS.put("Big Bottom", 753);
        SONG_IDS.put("Big Eyed Fish", 74);
        SONG_IDS.put("Big River", 2816);
        SONG_IDS.put("Billie Jean", 4872);
        SONG_IDS.put("Bird Song", 2817);
        SONG_IDS.put("Bismarck", 4875);
        SONG_IDS.put("Bitch", 548);
        SONG_IDS.put("Black Water", 479);
        SONG_IDS.put("Black and Blue Bird", 2828);
        SONG_IDS.put("Blackbird", 306);
        SONG_IDS.put("Blackjack", 648);
        SONG_IDS.put("Blister in the Sun", 664);
        SONG_IDS.put("Blitzkrieg Bop", 10930);
        SONG_IDS.put("Blue Scooter", 617);
        SONG_IDS.put("Blue Sky", 4897);
        SONG_IDS.put("Blue Water", 25);
        SONG_IDS.put("Bob Law", 4874);
        SONG_IDS.put("Born to Be Wild", 10927);
        SONG_IDS.put("Bouncing Around the Room", 407);
        SONG_IDS.put("Box of Rain", 2824);
        SONG_IDS.put("Boyd solo", 174);
        SONG_IDS.put("Brass Monkey", 727);
        SONG_IDS.put("Break Free", 374);
        SONG_IDS.put("Break for It", 471);
        SONG_IDS.put("Breathing Space", 135);
        SONG_IDS.put("Bridge of Sighs", 442);
        SONG_IDS.put("Broken Arrow", 2793);
        SONG_IDS.put("Broken Things", 728);
        SONG_IDS.put("Buena", 685);
        SONG_IDS.put("Buffalo Herds and Windmills", 384);
        SONG_IDS.put("Build You a House", 68);
        SONG_IDS.put("Build on Love", 530);
        SONG_IDS.put("Bul Ma Miin", 266);
        SONG_IDS.put("Burning Down the House", 557);
        SONG_IDS.put("Burning Love", 761);
        SONG_IDS.put("Burning Star", 722);
        SONG_IDS.put("Busted Stuff", 73);
        SONG_IDS.put("Butterfly", 260);
        SONG_IDS.put("Call It Even", 503);
        SONG_IDS.put("Call to the Post", 422);
        SONG_IDS.put("Can't Find My Way Home", 596);
        SONG_IDS.put("Can't Make Up", 5904);
        SONG_IDS.put("Can't Stop", 376);
        SONG_IDS.put("Can't You Hear Me Knocking", 261);
        SONG_IDS.put("Candyman", 505);
        SONG_IDS.put("Captain", 50);
        SONG_IDS.put("Careless Whisper", 514);
        SONG_IDS.put("Carter and Fishman Drum Duet", 491);
        SONG_IDS.put("Carter and Futureman Drum Duet", 3863);
        SONG_IDS.put("Carter solo", 691);
        SONG_IDS.put("Cassidy", 4896);
        SONG_IDS.put("Cause It's Time", 331);
        SONG_IDS.put("Cave, The", 736);
        SONG_IDS.put("Caveman", 607);
        SONG_IDS.put("Cello Suite No. 1 in G major, BWV 1007 - 3. Courante", 464);
        SONG_IDS.put("Center of Attention", 516);
        SONG_IDS.put("Charmed Life", 129);
        SONG_IDS.put("Chatterbox", 131);
        SONG_IDS.put("Che", 542);
        SONG_IDS.put("Cheap Sunglasses", 760);
        SONG_IDS.put("Chest Fever", 2807);
        SONG_IDS.put("China Cat Sunflower", 3872);
        SONG_IDS.put("Christmas Song", 31);
        SONG_IDS.put("Christmas Song, The", 3866);
        SONG_IDS.put("Christmas Time Is Here", 200);
        SONG_IDS.put("Cigarette Lit", 283);
        SONG_IDS.put("Cinnamon Girl", 230);
        SONG_IDS.put("Cissy Strut", 599);
        SONG_IDS.put("Clampdown", 764);
        SONG_IDS.put("Coast to Coast", 387);
        SONG_IDS.put("Colonel Bogey March", 2835);
        SONG_IDS.put("Come Away", 772);
        SONG_IDS.put("Come Together", 366);
        SONG_IDS.put("Communication", 314);
        SONG_IDS.put("Compared to What", 3847);
        SONG_IDS.put("Constantly", 3838);
        SONG_IDS.put("Continue", 465);
        SONG_IDS.put("Cool Day in May", 625);
        SONG_IDS.put("Corn Bread", 440);
        SONG_IDS.put("Cortez the Killer", 100);
        SONG_IDS.put("Cosmic Charlie", 4888);
        SONG_IDS.put("Could You Be Loved", 776);
        SONG_IDS.put("Counting the Stars", 9906);
        SONG_IDS.put("Crash into Me", 46);
        SONG_IDS.put("Crate of Gold", 5903);
        SONG_IDS.put("Crazy Easy", 277);
        SONG_IDS.put("Crazy Fingers", 2821);
        SONG_IDS.put("Crossroads", 3842);
        SONG_IDS.put("Crow & Sparrow", 3857);
        SONG_IDS.put("Crush", 55);
        SONG_IDS.put("Cry Freedom", 7);
        SONG_IDS.put("Cryptorchid", 101);
        SONG_IDS.put("Cum On Feel the Noize", 562);
        SONG_IDS.put("Cumberland Blues", 2810);
        SONG_IDS.put("Cupid's Pointy Arrow", 9916);
        SONG_IDS.put("Dancing Nancies", 20);
        SONG_IDS.put("Dancing in the Moonlight", 552);
        SONG_IDS.put("Dancing in the Street", 653);
        SONG_IDS.put("Dancing with Myself", 748);
        SONG_IDS.put("Danny Boy", 273);
        SONG_IDS.put("Dark Star", 2819);
        SONG_IDS.put("Darkness", 317);
        SONG_IDS.put("Daydream", 529);
        SONG_IDS.put("Days, The", 3839);
        SONG_IDS.put("Deal", 2794);
        SONG_IDS.put("Dear Mr. Fantasy", 2792);
        SONG_IDS.put("Death Don't Have No Mercy", 2812);
        SONG_IDS.put("Death on the High Seas", 2833);
        SONG_IDS.put("Decline in Reason", 222);
        SONG_IDS.put("Deed Is Done", 45);
        SONG_IDS.put("Delicate Balance", 447);
        SONG_IDS.put("Deliver Me", 460);
        SONG_IDS.put("Desert Mountain Showdown", 382);
        SONG_IDS.put("Destroyer", 666);
        SONG_IDS.put("Devil Woman", 4870);
        SONG_IDS.put("Diamonds on the Soles of Her Shoes", 2790);
        SONG_IDS.put("Diane", 474);
        SONG_IDS.put("Did You Ever Look So Nice?", 178);
        SONG_IDS.put("Didn't I", 9905);
        SONG_IDS.put("Digging a Ditch", 66);
        SONG_IDS.put("Dirty Water", 600);
        SONG_IDS.put("Disco", 477);
        SONG_IDS.put("Dive In", 575);
        SONG_IDS.put("Dodo", 249);
        SONG_IDS.put("Don't Burn the Pig", 152);
        SONG_IDS.put("Don't Drink the Water", 49);
        SONG_IDS.put("Don't Let Me Down", 639);
        SONG_IDS.put("Don't Think Twice, It's All Right", 593);
        SONG_IDS.put("Doobie Thing", 91);
        SONG_IDS.put("Doom", 446);
        SONG_IDS.put("Down by the River", 429);
        SONG_IDS.put("Down by the Riverside", 466);
        SONG_IDS.put("Dream Captain", 4868);
        SONG_IDS.put("Dream So Real, A", 483);
        SONG_IDS.put("Dreamed I Killed God", 52);
        SONG_IDS.put("Dreamgirl", 292);
        SONG_IDS.put("Dreaming Tree, The", 61);
        SONG_IDS.put("Dreams of Our Fathers", 81);
        SONG_IDS.put("Drive In Drive Out", 28);
        SONG_IDS.put("Driving Song", 394);
        SONG_IDS.put("Drums", 401);
        SONG_IDS.put("Drunken Soldier", 734);
        SONG_IDS.put("Dueling Banjos", 443);
        SONG_IDS.put("Eh Hee", 343);
        SONG_IDS.put("Elbow to Elbow", 681);
        SONG_IDS.put("Eleanor", 179);
        SONG_IDS.put("Eleanor Rigby", 4885);
        SONG_IDS.put("Elevator to the Moon", 3851);
        SONG_IDS.put("Endless Highway", 2802);
        SONG_IDS.put("Energy Change", 388);
        SONG_IDS.put("Entity", 683);
        SONG_IDS.put("Eternally", 468);
        SONG_IDS.put("Everybody Knows This Is Nowhere", 634);
        SONG_IDS.put("Everybody Wake Up (Our Finest Hour Arrives)", 298);
        SONG_IDS.put("Everyday", 76);
        SONG_IDS.put("Everything Is Broken", 390);
        SONG_IDS.put("Exodus", 102);
        SONG_IDS.put("Eyes of the World", 103);
        SONG_IDS.put("Falling Down", 506);
        SONG_IDS.put("Falling off the Roof", 472);
        SONG_IDS.put("Famous", 497);
        SONG_IDS.put("Farewell to the Old Me", 642);
        SONG_IDS.put("Fat Man in the Bathtub", 550);
        SONG_IDS.put("Feel Good", 461);
        SONG_IDS.put("Feel Like Makin' Love", 669);
        SONG_IDS.put("Feel Us Shaking", 180);
        SONG_IDS.put("Felíz Navidad", 622);
        SONG_IDS.put("Ferris Wheel", 658);
        SONG_IDS.put("Fire", 259);
        SONG_IDS.put("Fire on the Mountain", 4887);
        SONG_IDS.put("First Time Ever I Saw Your Face", 2836);
        SONG_IDS.put("Five to One", 762);
        SONG_IDS.put("Fixin' to Die", 536);
        SONG_IDS.put("Flat Foot Flewzy", 395);
        SONG_IDS.put("Fly Like an Eagle", 10931);
        SONG_IDS.put("Fly Me to the Moon", 610);
        SONG_IDS.put("Fly, The", 438);
        SONG_IDS.put("Fool in the Rain", 255);
        SONG_IDS.put("Fool to Think", 86);
        SONG_IDS.put("Footprints in the Snow", 495);
        SONG_IDS.put("For What It's Worth", 459);
        SONG_IDS.put("For You", 316);
        SONG_IDS.put("For the Beauty of Wynona", 104);
        SONG_IDS.put("Forsaken Savior", 771);
        SONG_IDS.put("Fragments", 498);
        SONG_IDS.put("Franklin's Tower", 2808);
        SONG_IDS.put("Free as a Bird", 9924);
        SONG_IDS.put("Friend of the Devil", 412);
        SONG_IDS.put("Funky Bitch", 339);
        SONG_IDS.put("Funny How Time Slips Away", 95);
        SONG_IDS.put("Funny the Way It Is", 579);
        SONG_IDS.put("GOD.FEAR.MONEY", 689);
        SONG_IDS.put("Gas into Fire", 350);
        SONG_IDS.put("Gaucho", 725);
        SONG_IDS.put("Get Together", 699);
        SONG_IDS.put("Get Up (I Feel Like Being A) Sex Machine", 215);
        SONG_IDS.put("Get You Moving", 3859);
        SONG_IDS.put("Get in Line", 38);
        SONG_IDS.put("Get on the Boat", 342);
        SONG_IDS.put("Ghost of Wimbledon, The", 355);
        SONG_IDS.put("Gimme Some Lovin'", 3868);
        SONG_IDS.put("Gimme Three Steps", 2826);
        SONG_IDS.put("Give Up the Goat", 9911);
        SONG_IDS.put("Glendale Train", 4876);
        SONG_IDS.put("Gloria", 365);
        SONG_IDS.put("Glory, Glory", 284);
        SONG_IDS.put("Go Outside and Drive", 360);
        SONG_IDS.put("God Save the Queen", 713);
        SONG_IDS.put("Going Up to the Country, Paint My Mailbox Blue", 367);
        SONG_IDS.put("Golden Road (to Unlimited Devotion), The", 4898);
        SONG_IDS.put("Good Good Time", 275);
        SONG_IDS.put("Good Morning Good Morning", 324);
        SONG_IDS.put("Good Times Bad Times", 686);
        SONG_IDS.put("Goodnight Elisabeth", 410);
        SONG_IDS.put("Goodnight My Friend", 507);
        SONG_IDS.put("Gotta Travel On", 698);
        SONG_IDS.put("Grab the Horns by the Bull", 9908);
        SONG_IDS.put("Grace Is Gone", 70);
        SONG_IDS.put("Granny", 30);
        SONG_IDS.put("Gravedigger", 205);
        SONG_IDS.put("Gravedigger intro", 203);
        SONG_IDS.put("Gravity", 485);
        SONG_IDS.put("Grazing in the Grass", 782);
        SONG_IDS.put("Great Blue Ocean", 385);
        SONG_IDS.put("Grey Blue Eyes", 244);
        SONG_IDS.put("Grey Street", 75);
        SONG_IDS.put("Grux", 582);
        SONG_IDS.put("Guantanamera", 7905);
        SONG_IDS.put("Gulf Coast Highway", 105);
        SONG_IDS.put("Hail to the Redskins", 687);
        SONG_IDS.put("Halloween", 29);
        SONG_IDS.put("Hanginaround", 409);
        SONG_IDS.put("Happier", 716);
        SONG_IDS.put("Happy Birthday to You", 211);
        SONG_IDS.put("Harder They Come, The", 268);
        SONG_IDS.put("Harvest", 208);
        SONG_IDS.put("Harvest Moon", 425);
        SONG_IDS.put("Have Yourself a Merry Little Christmas", 618);
        SONG_IDS.put("Healing Notion", 9918);
        SONG_IDS.put("Heard It in a Love Song", 721);
        SONG_IDS.put("Heart in Hand", 493);
        SONG_IDS.put("Heart of Gold", 322);
        SONG_IDS.put("Heartbeat Intro", 93);
        SONG_IDS.put("Heathcliff's Haiku Warriors", 35);
        SONG_IDS.put("Heaven", 396);
        SONG_IDS.put("Hedges/Oldfield medley", 559);
        SONG_IDS.put("Hello Again", 278);
        SONG_IDS.put("Help Myself", 24);
        SONG_IDS.put("Help on the Way", 2805);
        SONG_IDS.put("Hendrix/Beatles medley", 12926);
        SONG_IDS.put("Her Majesty", 420);
        SONG_IDS.put("Here Comes Santa Claus (Right Down Santa Claus Lane)", 619);
        SONG_IDS.put("Here Comes Sunshine", 2803);
        SONG_IDS.put("Here Comes the Sun", 4895);
        SONG_IDS.put("Here I Am", 240);
        SONG_IDS.put("Here On Out", 4877);
        SONG_IDS.put("Hey Bulldog", 250);
        SONG_IDS.put("Hey Girl", 3844);
        SONG_IDS.put("Hey Hey What Can I Do", 747);
        SONG_IDS.put("Hey Hey, My My (Into the Black)", 168);
        SONG_IDS.put("Hey Joe", 106);
        SONG_IDS.put("Hey Pocky Way", 700);
        SONG_IDS.put("Highway to Hell", 521);
        SONG_IDS.put("Hold Down the Block", 435);
        SONG_IDS.put("Hold Me Down", 43);
        SONG_IDS.put("Hold onto Your Heart", 3841);
        SONG_IDS.put("Homegrown", 655);
        SONG_IDS.put("Homeless", 2831);
        SONG_IDS.put("Honky Tonk Women", 789);
        SONG_IDS.put("Hopeful Heresy", 136);
        SONG_IDS.put("Hug", 1789);
        SONG_IDS.put("Humans from Earth", 190);
        SONG_IDS.put("Hunger for the Great Light", 290);
        SONG_IDS.put("Hurricane", 624);
        SONG_IDS.put("Hurt", 2797);
        SONG_IDS.put("I Did It", 79);
        SONG_IDS.put("I Got Love for You", 3855);
        SONG_IDS.put("I Got You Babe", 3867);
        SONG_IDS.put("I Got a Woman", 609);
        SONG_IDS.put("I Know You Rider", 3874);
        SONG_IDS.put("I Need a Word", 778);
        SONG_IDS.put("I Remember You", 751);
        SONG_IDS.put("I Saw Her Standing There", 263);
        SONG_IDS.put("I Saw the Light", 6905);
        SONG_IDS.put("I Second That Emotion", 701);
        SONG_IDS.put("I Shall Be Released", 632);
        SONG_IDS.put("I Wanna Be Sedated", 665);
        SONG_IDS.put("I Wanna Be Your Lover", 4871);
        SONG_IDS.put("I Wanna Rock", 564);
        SONG_IDS.put("I Want You (She's So Heavy)", 10932);
        SONG_IDS.put("I Want to Take You Higher", 369);
        SONG_IDS.put("I Will Wait", 381);
        SONG_IDS.put("I Won't Give It Away", 352);
        SONG_IDS.put("I'll Back You Up", 1);
        SONG_IDS.put("I'll Be There", 603);
        SONG_IDS.put("I'll Fly Away", 6904);
        SONG_IDS.put("I'm Alive", 558);
        SONG_IDS.put("I'm Not Alone", 397);
        SONG_IDS.put("I'm Shipping Up to Boston", 644);
        SONG_IDS.put("I'm Your Captain", 430);
        SONG_IDS.put("Idea of You, The", 370);
        SONG_IDS.put("If I Had It All", 84);
        SONG_IDS.put("If I Had a Boat", 107);
        SONG_IDS.put("If I Were Crazy intro", 161);
        SONG_IDS.put("If Only", 726);
        SONG_IDS.put("If You've Got the Time, We've Got the Beer", 788);
        SONG_IDS.put("If the Ocean Had Its Way", 657);
        SONG_IDS.put("Iko Iko", 344);
        SONG_IDS.put("Imagine", 241);
        SONG_IDS.put("Imagine This", 554);
        SONG_IDS.put("Immigrant Song", 216);
        SONG_IDS.put("Impermanence", 219);
        SONG_IDS.put("Improv jam", 127);
        SONG_IDS.put("In Memory of Elizabeth Reed", 758);
        SONG_IDS.put("In My Life", 169);
        SONG_IDS.put("In November Sunlight", 337);
        SONG_IDS.put("In This Place", 441);
        SONG_IDS.put("In Your Eyes", 12925);
        SONG_IDS.put("In the Attics of My Life", 2798);
        SONG_IDS.put("In-A-Gadda-Da-Vida", 565);
        SONG_IDS.put("Instant Karma!", 636);
        SONG_IDS.put("Is Anybody Here?", 162);
        SONG_IDS.put("Is Chicago, Is Not Chicago", 108);
        SONG_IDS.put("It's Alright", 229);
        SONG_IDS.put("It's the End of the World As We Know It (And I Feel Fine)", 746);
        SONG_IDS.put("Iwoya", 313);
        SONG_IDS.put("JTR", 63);
        SONG_IDS.put("Jack the Rabbit", 3850);
        SONG_IDS.put("Japan", 502);
        SONG_IDS.put("Jemez Rolling Waves", 137);
        SONG_IDS.put("Jessica", 406);
        SONG_IDS.put("Jimi Thing", 19);
        SONG_IDS.put("Jimmy Olsen's Blues", 14925);
        SONG_IDS.put("Jiriki", 318);
        SONG_IDS.put("Johnny B. Goode", 10933);
        SONG_IDS.put("Joyful Girl", 308);
        SONG_IDS.put("Joyride", 276);
        SONG_IDS.put("Jumpin' Jack Flash", 790);
        SONG_IDS.put("Just Another Whistle Stop", 2815);
        SONG_IDS.put("Just What I Needed", 745);
        SONG_IDS.put("Just a Little Light", 2814);
        SONG_IDS.put("Kashmir", 458);
        SONG_IDS.put("Kilimanjaro", 3861);
        SONG_IDS.put("Kill the King", 372);
        SONG_IDS.put("Kill the Preacher", 767);
        SONG_IDS.put("Kind Intentions", 32);
        SONG_IDS.put("King of the Bling", 601);
        SONG_IDS.put("Kit Kat Jam", 71);
        SONG_IDS.put("Kneeknocker", 404);
        SONG_IDS.put("Kookaburra", 291);
        SONG_IDS.put("Kundalini Bonfire", 217);
        SONG_IDS.put("L.A. Woman", 10928);
        SONG_IDS.put("Land of Promise", 640);
        SONG_IDS.put("Last Night", 744);
        SONG_IDS.put("Last Stop, The", 60);
        SONG_IDS.put("Late in the Evening", 2829);
        SONG_IDS.put("Lay Down", 5901);
        SONG_IDS.put("LeRoi solo", 155);
        SONG_IDS.put("Leave Me Praying", 167);
        SONG_IDS.put("Let It Bleed", 428);
        SONG_IDS.put("Let It Grow", 4889);
        SONG_IDS.put("Let Me Be Your God", 4867);
        SONG_IDS.put("Let You Down", 39);
        SONG_IDS.put("Let's Dance", 718);
        SONG_IDS.put("Letter from a Friend", 358);
        SONG_IDS.put("Letting Go", 133);
        SONG_IDS.put("Lie in Our Graves", 22);
        SONG_IDS.put("Life Is Better with You", 3854);
        SONG_IDS.put("Life in the City", 501);
        SONG_IDS.put("Light Lift Me Up", 88);
        SONG_IDS.put("Like a Hurricane", 694);
        SONG_IDS.put("Limelight", 719);
        SONG_IDS.put("Linus and Lucy", 153);
        SONG_IDS.put("Listen", 330);
        SONG_IDS.put("Litho Blitho", 349);
        SONG_IDS.put("Little Red Bird", 588);
        SONG_IDS.put("Little Sparrow", 2813);
        SONG_IDS.put("Little Thing", 48);
        SONG_IDS.put("Little Too Late", 3843);
        SONG_IDS.put("Little Wing", 4881);
        SONG_IDS.put("Lively Up Yourself", 375);
        SONG_IDS.put("Long Black Veil", 109);
        SONG_IDS.put("Long December", 408);
        SONG_IDS.put("Long Time to Wait", 332);
        SONG_IDS.put("Look at Miss Ohio", 2795);
        SONG_IDS.put("Look on Yonder Wall", 568);
        SONG_IDS.put("Looking at You", 53);
        SONG_IDS.put("Loose Interpretation", 160);
        SONG_IDS.put("Los Alamos Is Burning", 224);
        SONG_IDS.put("Lost in the Supermarket", 518);
        SONG_IDS.put("Louisiana Bayou", 295);
        SONG_IDS.put("Love Hurts", 419);
        SONG_IDS.put("Love Is the Only Way", 336);
        SONG_IDS.put("Love Tractor", 478);
        SONG_IDS.put("Love Will Keep Us Together", 740);
        SONG_IDS.put("Love of My Life", 64);
        SONG_IDS.put("Love the One You're With", 556);
        SONG_IDS.put("Lover Lay Down", 8);
        SONG_IDS.put("Loving Wings", 210);
        SONG_IDS.put("Low Rider", 511);
        SONG_IDS.put("Lower Voice", 319);
        SONG_IDS.put("Lucy in the Sky with Diamonds", 4892);
        SONG_IDS.put("Lullaby", 418);
        SONG_IDS.put("Lying in the Hands of God", 571);
        SONG_IDS.put("Mac Head", 62);
        SONG_IDS.put("Madame Trudeaux", 1791);
        SONG_IDS.put("Maggie's Farm", 393);
        SONG_IDS.put("Make Somebody Happy", 264);
        SONG_IDS.put("Maker, The", 121);
        SONG_IDS.put("Mamma Boulet", 531);
        SONG_IDS.put("Man Who Would Be Santa, The", 496);
        SONG_IDS.put("Manfood", 9909);
        SONG_IDS.put("Manhattan Bridge", 490);
        SONG_IDS.put("Many Rivers to Cross", 647);
        SONG_IDS.put("Mark and Carter Jam", 602);
        SONG_IDS.put("Mason's Children", 4886);
        SONG_IDS.put("Me and Bobby McGee", 704);
        SONG_IDS.put("Me and Her", 183);
        SONG_IDS.put("Me and Julio Down by the Schoolyard", 110);
        SONG_IDS.put("Melissa", 486);
        SONG_IDS.put("Memory Motel", 353);
        SONG_IDS.put("Mercy", 723);
        SONG_IDS.put("Mercy Street", 139);
        SONG_IDS.put("Message in a Bottle", 735);
        SONG_IDS.put("Metamorphosis", 227);
        SONG_IDS.put("Midnight Highway", 2818);
        SONG_IDS.put("Midnight Moonlight", 707);
        SONG_IDS.put("Minarets", 18);
        SONG_IDS.put("Miserlou", 674);
        SONG_IDS.put("Miss You", 717);
        SONG_IDS.put("Modern Grip", 3862);
        SONG_IDS.put("Money", 546);
        SONG_IDS.put("Money (That's What I Want)", 547);
        SONG_IDS.put("Monkey Man", 72);
        SONG_IDS.put("Monster's Lullaby", 4869);
        SONG_IDS.put("Morning Dew", 4891);
        SONG_IDS.put("Mother Father", 85);
        SONG_IDS.put("Mother of Africa", 9914);
        SONG_IDS.put("Mother's Little Helper", 663);
        SONG_IDS.put("Mother's Night", 145);
        SONG_IDS.put("Mountain Song", 2804);
        SONG_IDS.put("Mountains of the Moon", 2822);
        SONG_IDS.put("Mulling It Over", 364);
        SONG_IDS.put("Muros y Puertas", 7904);
        SONG_IDS.put("My Antonia", 111);
        SONG_IDS.put("My My, Hey Hey (Out of the Blue)", 783);
        SONG_IDS.put("My Way", 679);
        SONG_IDS.put("Nature", 184);
        SONG_IDS.put("Needle and the Damage Done, The", 628);
        SONG_IDS.put("Next Time You See Me", 3870);
        SONG_IDS.put("Night Shift", 715);
        SONG_IDS.put("Nightrain", 714);
        SONG_IDS.put("No Depression in Heaven", 594);
        SONG_IDS.put("No Egos Underwater", 538);
        SONG_IDS.put("No Woman, No Cry", 737);
        SONG_IDS.put("Nobody", 454);
        SONG_IDS.put("Non-Violent Approach", 626);
        SONG_IDS.put("None of Us Are Free", 453);
        SONG_IDS.put("Norwegian Wood (This Bird Has Flown)", 305);
        SONG_IDS.put("Not Fade Away", 4894);
        SONG_IDS.put("Nothing Lasts for Long", 615);
        SONG_IDS.put("Nothing from Nothing", 469);
        SONG_IDS.put("November '94 Jam", 777);
        SONG_IDS.put("O Canada", 739);
        SONG_IDS.put("O Little Town of Bethlehem", 544);
        SONG_IDS.put("Oceans of War", 185);
        SONG_IDS.put("Ode to the Box", 9919);
        SONG_IDS.put("Oh", 236);
        SONG_IDS.put("Oh Bangladesh", 651);
        SONG_IDS.put("Oh Mistress Mine", 773);
        SONG_IDS.put("Oh Susannah", 697);
        SONG_IDS.put("Oh, Sister", 254);
        SONG_IDS.put("Ohio", 218);
        SONG_IDS.put("Old Dirt Hill (Bring That Beat Back)", 289);
        SONG_IDS.put("Olé, Olé, Olé", 766);
        SONG_IDS.put("Once on a Wild Afternoon", 26);
        SONG_IDS.put("One", 581);
        SONG_IDS.put("One Sweet World", 12);
        SONG_IDS.put("One Way Out", 660);
        SONG_IDS.put("One of the Best Ones", 708);
        SONG_IDS.put("Only Love Can Break Your Heart", 482);
        SONG_IDS.put("Open Up, Let It In", 159);
        SONG_IDS.put("Open Your Mind", 379);
        SONG_IDS.put("Other One, The", 2811);
        SONG_IDS.put("Out of My Hands", 299);
        SONG_IDS.put("Over the Rainbow", 362);
        SONG_IDS.put("Overdue", 612);
        SONG_IDS.put("Paint It Black", 10929);
        SONG_IDS.put("Pantala Naga Pampa", 57);
        SONG_IDS.put("Papa Was a Rolling Stone", 455);
        SONG_IDS.put("Pata Pata", 793);
        SONG_IDS.put("Pawn Shop", 421);
        SONG_IDS.put("Pay Day", 3853);
        SONG_IDS.put("Pay for What You Get", 23);
        SONG_IDS.put("People", 4901);
        SONG_IDS.put("People Have the Power", 426);
        SONG_IDS.put("People People", 14);
        SONG_IDS.put("Perfect World", 333);
        SONG_IDS.put("Piece of My Heart", 270);
        SONG_IDS.put("Pig", 42);
        SONG_IDS.put("Pinch Me", 517);
        SONG_IDS.put("Pirate Looks at Forty, A", 540);
        SONG_IDS.put("Plain or Peanut", 3845);
        SONG_IDS.put("Plastic Girl", 4878);
        SONG_IDS.put("Playing in the Band", 4880);
        SONG_IDS.put("Polgreen, Sight-Reading", 608);
        SONG_IDS.put("Porch Song", 356);
        SONG_IDS.put("Prelude to Grace", 151);
        SONG_IDS.put("Pretty Bird", 9910);
        SONG_IDS.put("Pretty Vacant", 661);
        SONG_IDS.put("Promise of Tomorrow", 509);
        SONG_IDS.put("Proudest Monkey", 44);
        SONG_IDS.put("Psycho Killer", 513);
        SONG_IDS.put("Pure Imagination", 439);
        SONG_IDS.put("Radar", 311);
        SONG_IDS.put("Radar Contact", 225);
        SONG_IDS.put("Rain Down on Me", 156);
        SONG_IDS.put("Rain King", 411);
        SONG_IDS.put("Rain intro", 206);
        SONG_IDS.put("Rainy Day Women #12 & 35", 392);
        SONG_IDS.put("Rapunzel", 56);
        SONG_IDS.put("Raven", 69);
        SONG_IDS.put("Rebel Rebel", 678);
        SONG_IDS.put("Recently", 3);
        SONG_IDS.put("Red Rain", 463);
        SONG_IDS.put("Red Red Wine", 598);
        SONG_IDS.put("Redemption Song", 112);
        SONG_IDS.put("Repeat the Question", 141);
        SONG_IDS.put("Revolution", 662);
        SONG_IDS.put("Rheginos and the Resurrection", 142);
        SONG_IDS.put("Rhiannon", 635);
        SONG_IDS.put("Rhyme & Reason", 33);
        SONG_IDS.put("Richmond Jam", 321);
        SONG_IDS.put("Ride, The", 508);
        SONG_IDS.put("Riders on the Storm", 398);
        SONG_IDS.put("Riff, The", 730);
        SONG_IDS.put("Right On Be Free", 265);
        SONG_IDS.put("Right Place, Wrong Time", 269);
        SONG_IDS.put("Ring of Fire", 237);
        SONG_IDS.put("Risen", 413);
        SONG_IDS.put("River Deep – Mountain High", 2820);
        SONG_IDS.put("Road", 606);
        SONG_IDS.put("Rock You Like a Hurricane", 563);
        SONG_IDS.put("Rockin' in the Free World", 285);
        SONG_IDS.put("Rocky Mountain Way", 323);
        SONG_IDS.put("Roll Up", 457);
        SONG_IDS.put("Rooftop", 732);
        SONG_IDS.put("Root Down", 2827);
        SONG_IDS.put("Round and Round", 492);
        SONG_IDS.put("Round and Round [Ratt]", 620);
        SONG_IDS.put("Route 2", 186);
        SONG_IDS.put("Rudolph the Red-Nosed Reindeer", 573);
        SONG_IDS.put("Run", 334);
        SONG_IDS.put("Runnin' Down a Dream", 742);
        SONG_IDS.put("Rye Whiskey", 590);
        SONG_IDS.put("Sad and Deep as You", 403);
        SONG_IDS.put("Sail Away", 553);
        SONG_IDS.put("Salty Dog", 3849);
        SONG_IDS.put("Samurai Cop", 4873);
        SONG_IDS.put("Satellite", 11);
        SONG_IDS.put("Satellite [Guster]", 1790);
        SONG_IDS.put("Satisfy", 690);
        SONG_IDS.put("Saturday Night Special", 763);
        SONG_IDS.put("Save Me", 235);
        SONG_IDS.put("Say Goodbye", 37);
        SONG_IDS.put("Scarlet Begonias", 451);
        SONG_IDS.put("Seanny Boy (Drop Out)", 616);
        SONG_IDS.put("See Jane", 194);
        SONG_IDS.put("Seek Up", 27);
        SONG_IDS.put("Seven", 584);
        SONG_IDS.put("Sex in a Pan", 400);
        SONG_IDS.put("Sexy M.F.", 605);
        SONG_IDS.put("Shake Me Like a Monkey", 574);
        SONG_IDS.put("Shakedown Street", 4899);
        SONG_IDS.put("She's a Woman", 9915);
        SONG_IDS.put("Shimmer", 560);
        SONG_IDS.put("Ship Song, The", 452);
        SONG_IDS.put("Shoeless Joe", 684);
        SONG_IDS.put("Shotgun", 373);
        SONG_IDS.put("Should I Stay or Should I Go", 673);
        SONG_IDS.put("Shout It Out Loud", 561);
        SONG_IDS.put("Show Me", 328);
        SONG_IDS.put("Silence Must Be Killed", 743);
        SONG_IDS.put("Since We First Met", 522);
        SONG_IDS.put("Sinceritox", 656);
        SONG_IDS.put("Sing Along", 309);
        SONG_IDS.put("Sister", 304);
        SONG_IDS.put("Sister [1994]", 371);
        SONG_IDS.put("Sledgehammer", 549);
        SONG_IDS.put("Sleep", 611);
        SONG_IDS.put("Sleep to Dream Her", 87);
        SONG_IDS.put("Slip Slidin' Away", 784);
        SONG_IDS.put("Slipknot", 2806);
        SONG_IDS.put("Smooth Rider", 294);
        SONG_IDS.put("Snow Outside", 733);
        SONG_IDS.put("So Damn Lucky", 233);
        SONG_IDS.put("So Glad", 329);
        SONG_IDS.put("So Lonely", 415);
        SONG_IDS.put("So Much to Say", 21);
        SONG_IDS.put("So Right", 83);
        SONG_IDS.put("So What", 786);
        SONG_IDS.put("Solsbury Hill", 242);
        SONG_IDS.put("Some Devil", 238);
        SONG_IDS.put("Song 2", 720);
        SONG_IDS.put("Song That Jane Likes, The", 2);
        SONG_IDS.put("Song for Billijo", 8906);
        SONG_IDS.put("Soul Refreshing", 456);
        SONG_IDS.put("Soul Shakedown", 759);
        SONG_IDS.put("Sound of Silence, The", 4884);
        SONG_IDS.put("Southbound", 543);
        SONG_IDS.put("Southern Man", 688);
        SONG_IDS.put("Sower of Words", 437);
        SONG_IDS.put("Space Between, The", 80);
        SONG_IDS.put("Space Is the Place", 535);
        SONG_IDS.put("Spaceman", 576);
        SONG_IDS.put("Spain", 402);
        SONG_IDS.put("Spanish Moon", 187);
        SONG_IDS.put("Speakers", 709);
        SONG_IDS.put("Spider Web, The", 9925);
        SONG_IDS.put("Spinning Spiraling Machine", 359);
        SONG_IDS.put("Spoon", 54);
        SONG_IDS.put("Spoonful of Sugar, A", 695);
        SONG_IDS.put("Spotlight", 16);
        SONG_IDS.put("Spy Girl 76", 380);
        SONG_IDS.put("Squirm", 577);
        SONG_IDS.put("St. Stephen", 2799);
        SONG_IDS.put("Stagger Lee", 2796);
        SONG_IDS.put("Stairway to Heaven", 4890);
        SONG_IDS.put("Stand", 361);
        SONG_IDS.put("Stand Up (For It)", 288);
        SONG_IDS.put("Stand by Me", 597);
        SONG_IDS.put("Standing on Shaky Ground", 706);
        SONG_IDS.put("Star Wars Main Title", 629);
        SONG_IDS.put("Star-Spangled Banner, The", 433);
        SONG_IDS.put("Stay (Wasting Time)", 59);
        SONG_IDS.put("Stay or Leave", 220);
        SONG_IDS.put("Steady as We Go", 296);
        SONG_IDS.put("Stefan's Tune", 3865);
        SONG_IDS.put("Still Water", 445);
        SONG_IDS.put("Stir It Up", 113);
        SONG_IDS.put("Stolen Away on 55th & 3rd", 300);
        SONG_IDS.put("Stomping Grounds", 555);
        SONG_IDS.put("Stone, The", 58);
        SONG_IDS.put("Stranger in a Strained Land", 223);
        SONG_IDS.put("Stream", 130);
        SONG_IDS.put("Strong Hand (Just One Miracle)", 239);
        SONG_IDS.put("Stuck on You", 213);
        SONG_IDS.put("Suddenly I See", 1792);
        SONG_IDS.put("Sugar Man", 781);
        SONG_IDS.put("Sugar Will", 279);
        SONG_IDS.put("Sugaree", 2809);
        SONG_IDS.put("Sullivan Street", 424);
        SONG_IDS.put("Summer Night in December", 9907);
        SONG_IDS.put("Sunday Morning", 637);
        SONG_IDS.put("Sunrays and Saturdays", 504);
        SONG_IDS.put("Super Bowl Sundae", 489);
        SONG_IDS.put("Super Freak", 282);
        SONG_IDS.put("Superman", 519);
        SONG_IDS.put("Superstition", 253);
        SONG_IDS.put("Sweet", 693);
        SONG_IDS.put("Sweet Caroline", 377);
        SONG_IDS.put("Sweet Child o' Mine", 752);
        SONG_IDS.put("Sweet Emotion", 671);
        SONG_IDS.put("Sweet Home Alabama", 115);
        SONG_IDS.put("Sweet Up and Down", 67);
        SONG_IDS.put("Sweetheart", 13925);
        SONG_IDS.put("Sympathy for the Devil", 117);
        SONG_IDS.put("Take Me Out to the Ball Game", 646);
        SONG_IDS.put("Take Me to Tomorrow", 738);
        SONG_IDS.put("Take Me to the River", 118);
        SONG_IDS.put("Take Out, The", 476);
        SONG_IDS.put("Take the Time", 659);
        SONG_IDS.put("Tangerine", 119);
        SONG_IDS.put("Tangled Web We Weave, A", 4900);
        SONG_IDS.put("Taps", 286);
        SONG_IDS.put("Taxman", 3860);
        SONG_IDS.put("Teach Your Children", 8905);
        SONG_IDS.put("Tell Me Something Good", 252);
        SONG_IDS.put("Temple, The", 122);
        SONG_IDS.put("Tempo Feliz", 11925);
        SONG_IDS.put("Ten Years Gone", 475);
        SONG_IDS.put("Thank You (Falettinme Be Mice Elf Agin)", 257);
        SONG_IDS.put("Theme from The Flintstones", 120);
        SONG_IDS.put("Theme from the Bottom", 340);
        SONG_IDS.put("They Love Each Other", 3869);
        SONG_IDS.put("Thief & the Heartbreaker, The", 5902);
        SONG_IDS.put("Thing That Happens, A", 274);
        SONG_IDS.put("This Land Is Your Land", 417);
        SONG_IDS.put("Three Little Birds", 258);
        SONG_IDS.put("Timber & Blood", 3856);
        SONG_IDS.put("Time", 741);
        SONG_IDS.put("Time After Time", 267);
        SONG_IDS.put("Time Bomb", 578);
        SONG_IDS.put("Time Flack", 3852);
        SONG_IDS.put("Time Is Free", 533);
        SONG_IDS.put("Time for It", 9923);
        SONG_IDS.put("Time of the Season", 303);
        SONG_IDS.put("Times They Are A-Changin', The", 391);
        SONG_IDS.put("To Touch Yearning", 143);
        SONG_IDS.put("Tomorrow Never Knows", 631);
        SONG_IDS.put("Too High", 248);
        SONG_IDS.put("Too Much", 47);
        SONG_IDS.put("Touch Me", 711);
        SONG_IDS.put("Touch of Grey", 4893);
        SONG_IDS.put("Toy Soldiers", 51);
        SONG_IDS.put("Train in Vain", 668);
        SONG_IDS.put("Tree of Life", 189);
        SONG_IDS.put("Tremendous Brunettes", 312);
        SONG_IDS.put("Trilogy", 378);
        SONG_IDS.put("Tripping Billies", 6);
        SONG_IDS.put("Trondossa", 537);
        SONG_IDS.put("Trouble", 243);
        SONG_IDS.put("Trouble and Strife", 315);
        SONG_IDS.put("Trouble with You", 302);
        SONG_IDS.put("True Dreams of Wichita", 654);
        SONG_IDS.put("True Reflections", 15);
        SONG_IDS.put("Tubby", 692);
        SONG_IDS.put("Tupelo Honey", 2837);
        SONG_IDS.put("Turn It into Love", 212);
        SONG_IDS.put("Tutu", 710);
        SONG_IDS.put("Two Step", 13);
        SONG_IDS.put("Two Truckloads", 3846);
        SONG_IDS.put("Typical Situation", 9);
        SONG_IDS.put("Umama", 779);
        SONG_IDS.put("Unbroken Chain", 4883);
        SONG_IDS.put("Uncle John's Band", 2823);
        SONG_IDS.put("Under the Bridge", 3858);
        SONG_IDS.put("Under the Milky Way", 670);
        SONG_IDS.put("Uninvited", 414);
        SONG_IDS.put("Up and Away", 246);
        SONG_IDS.put("Up in the Air", 3837);
        SONG_IDS.put("Up on Cripple Creek", 245);
        SONG_IDS.put("Viola Lee Blues", 3873);
        SONG_IDS.put("Virginia in the Rain", 2832);
        SONG_IDS.put("Wake the Funk Up", 4879);
        SONG_IDS.put("Walk This Way", 672);
        SONG_IDS.put("Walk of Shame", 724);
        SONG_IDS.put("War Pigs", 231);
        SONG_IDS.put("Warehouse", 5);
        SONG_IDS.put("Wash Away", 494);
        SONG_IDS.put("Waste", 124);
        SONG_IDS.put("Watcher of the Skies", 13926);
        SONG_IDS.put("Watching the Wheels", 325);
        SONG_IDS.put("Water into Wine", 128);
        SONG_IDS.put("Watermelon Man", 416);
        SONG_IDS.put("Watermelon Smilin' on the Vine", 123);
        SONG_IDS.put("Wayfarer, The", 228);
        SONG_IDS.put("We Are the World", 232);
        SONG_IDS.put("We Belong Together", 785);
        SONG_IDS.put("We Got the Neutron Bomb", 10926);
        SONG_IDS.put("We're Not Gonna Take It", 520);
        SONG_IDS.put("We've Got Tonight", 769);
        SONG_IDS.put("Weeping", 792);
        SONG_IDS.put("Weight of the World", 756);
        SONG_IDS.put("Weight, The", 405);
        SONG_IDS.put("West L.A. Fadeaway", 3871);
        SONG_IDS.put("What Do You Want from Me Now", 383);
        SONG_IDS.put("What Will Become of Me", 94);
        SONG_IDS.put("What Would You Say", 10);
        SONG_IDS.put("What You Are", 82);
        SONG_IDS.put("What You Wish For", 621);
        SONG_IDS.put("What a Time for Love", 335);
        SONG_IDS.put("What the World Needs Now Is Love", 757);
        SONG_IDS.put("What's Going On", 399);
        SONG_IDS.put("Whatever Gets You Thru the Night", 368);
        SONG_IDS.put("Wheel, The", 4882);
        SONG_IDS.put("When the World Ends", 77);
        SONG_IDS.put("Where Are You Going", 90);
        SONG_IDS.put("Whipping Post", 432);
        SONG_IDS.put("Whispering Pines", 643);
        SONG_IDS.put("White Room", 515);
        SONG_IDS.put("Whiter Shade of Pale, A", 680);
        SONG_IDS.put("Whole Lotta Love", 436);
        SONG_IDS.put("Why (What's Goin On?)", 467);
        SONG_IDS.put("Why I Am", 583);
        SONG_IDS.put("Wild Horses", 125);
        SONG_IDS.put("Will It Go Round in Circles", 251);
        SONG_IDS.put("Will the Circle Be Unbroken?", 595);
        SONG_IDS.put("Witness", 434);
        SONG_IDS.put("Wonder Twins", 320);
        SONG_IDS.put("Words (Between the Lines of Age)", 462);
        SONG_IDS.put("Work It Out", 351);
        SONG_IDS.put("Working on a Building", 539);
        SONG_IDS.put("World's Not Falling Apart, The", 641);
        SONG_IDS.put("Worried Man Blues", 9912);
        SONG_IDS.put("Write a Song", 589);
        SONG_IDS.put("Year 1812, The", 3864);
        SONG_IDS.put("Yesterday", 787);
        SONG_IDS.put("Yield Not to Temptation", 3848);
        SONG_IDS.put("You & Me", 586);
        SONG_IDS.put("You Ain't Seen Nothing Yet", 765);
        SONG_IDS.put("You Are My Sanity", 132);
        SONG_IDS.put("You Can't Stop Rock 'n' Roll", 712);
        SONG_IDS.put("You Enjoy Myself", 338);
        SONG_IDS.put("You Might Die Trying", 301);
        SONG_IDS.put("You Never Know", 202);
        SONG_IDS.put("You Should Know Me", 650);
        SONG_IDS.put("You Won't See Me", 126);
        SONG_IDS.put("Your Steps Alone", 386);
        SONG_IDS.put("Youth Gone Wild", 750);
        SONG_IDS.put("Zambi", 534);
    }

    private Songs() {}

    static Integer get(String name) {
        return SONG_IDS.entrySet()
                .stream()
                .sorted(Comparator.comparing(song -> LEVENSHTEIN_DISTANCE.apply(song.getKey(), name)))
                .map(Map.Entry::getValue)
                .findFirst()
                .orElse(null);
    }
}
